version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: ./dockerfile
    ports:
      - 3004:3004

  ui:
    image: ui
    depends_on:
      - api
    build:
      context: certiui
      dockerfile: ./dockerfile
    ports:
      - 3010:3010

volumes:
  mongo_volume: